project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.ipynb
        text: "About Me"
      - text: "My Slides"
        href: slides/slides.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true



